'use strict';
const params=new URLSearchParams(location.search);
let language=params.get('lang')==='en'?'en':'fa';
let currentSlide=0,paused=false,timer=null;
const slides=[...document.querySelectorAll('.slide')];
const words={fa:{pause:'توقف',play:'پخش',status:'متن ایمیل آماده است. ارسال را در برنامه ایمیل تکمیل کنید. اگر برنامه باز نشد، مستقیم به ppm.co2023@gmail.com ایمیل بفرستید.'},en:{pause:'Pause',play:'Play',status:'Your email is ready. Complete sending in your email app. If it does not open, email ppm.co2023@gmail.com directly.'}};
function localLinks(){document.querySelectorAll('a[href]').forEach(a=>{const raw=a.getAttribute('href');if(!raw||raw.startsWith('#')||/^[a-z]+:/i.test(raw))return;const [path,query='']=raw.split('?');if(!path.endsWith('.html'))return;const q=new URLSearchParams(query);if(language==='en')q.set('lang','en');else q.delete('lang');a.setAttribute('href',path+(q.size?'?'+q.toString():''));});}
function pauseLabel(){const p=document.getElementById('pause');if(p){p.textContent=paused?words[language].play:words[language].pause;p.setAttribute('aria-pressed',String(paused));}}
function updateLanguage(){document.documentElement.lang=language;document.documentElement.dir=language==='fa'?'rtl':'ltr';document.querySelectorAll('[data-fa][data-en]').forEach(e=>e.textContent=e.dataset[language]);const b=document.getElementById('language');b.textContent=language==='fa'?'EN':'فا';b.setAttribute('aria-label',language==='fa'?'Switch to English':'تغییر زبان به فارسی');document.title=document.body.dataset[language==='fa'?'titleFa':'titleEn']+' | '+(language==='fa'?'پایش پژوهش محیط':'PPM');document.querySelector('meta[name=description]').content=document.title;localLinks();pauseLabel();const status=document.getElementById('form-status');if(status)status.textContent='';}
document.getElementById('language').addEventListener('click',()=>{language=language==='fa'?'en':'fa';updateLanguage();try{const u=new URL(location.href);u.searchParams.set('lang',language);history.replaceState(null,'',u)}catch{}});
const menu=document.querySelector('.menu-toggle'),nav=document.getElementById('navigation');
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));});document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}});
function showSlide(i){currentSlide=(i+slides.length)%slides.length;slides.forEach((s,j)=>s.hidden=j!==currentSlide);document.querySelectorAll('.slide-dot').forEach((b,j)=>b.setAttribute('aria-pressed',String(j===currentSlide)));}
function startTimer(){clearInterval(timer);if(slides.length&&!paused&&!document.hidden)timer=setInterval(()=>showSlide(currentSlide+1),3000);}
if(slides.length){paused=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const region=document.querySelector('.slider');document.getElementById('prev').addEventListener('click',()=>{showSlide(currentSlide-1);startTimer();});document.getElementById('next').addEventListener('click',()=>{showSlide(currentSlide+1);startTimer();});document.querySelectorAll('.slide-dot').forEach(b=>b.addEventListener('click',()=>{showSlide(Number(b.dataset.slide));startTimer();}));document.getElementById('pause').addEventListener('click',()=>{paused=!paused;pauseLabel();startTimer();});region.addEventListener('mouseenter',()=>clearInterval(timer));region.addEventListener('mouseleave',startTimer);region.addEventListener('focusin',()=>clearInterval(timer));region.addEventListener('focusout',e=>{if(!region.contains(e.relatedTarget))startTimer();});document.addEventListener('visibilitychange',startTimer);startTimer();}
const form=document.getElementById('inquiry-form');if(form){const select=document.getElementById('subject');if([...select.options].some(o=>o.value===params.get('product')))select.value=params.get('product');form.addEventListener('submit',e=>{e.preventDefault();const n=document.getElementById('name').value.trim(),m=document.getElementById('message').value.trim();if(!n||!m)return;const body=(language==='fa'?'نام / سازمان: ':'Name / organization: ')+n+'\n\n'+m;const subject=select.selectedOptions[0].textContent;document.getElementById('form-status').textContent=words[language].status;location.href='mailto:ppm.co2023@gmail.com?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);});}
updateLanguage();
